
// This file has been generated by the GUI designer. Do not modify.
namespace mhe
{
	public partial class Vec3Widget
	{
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.EventBox X_eventBox;
		
		private global::Gtk.Label X_label;
		
		private global::Gtk.SpinButton spinbutton2;
		
		private global::Gtk.EventBox Y_eventBox;
		
		private global::Gtk.Label Y_label;
		
		private global::Gtk.SpinButton spinbutton4;
		
		private global::Gtk.EventBox Z_eventBox;
		
		private global::Gtk.Label Z_label;
		
		private global::Gtk.SpinButton spinbutton3;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget mhe.Vec3Widget
			global::Stetic.BinContainer.Attach (this);
			this.HeightRequest = 32;
			this.Name = "mhe.Vec3Widget";
			// Container child mhe.Vec3Widget.Gtk.Container+ContainerChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.X_eventBox = new global::Gtk.EventBox ();
			this.X_eventBox.WidthRequest = 32;
			this.X_eventBox.Name = "X_eventBox";
			// Container child X_eventBox.Gtk.Container+ContainerChild
			this.X_label = new global::Gtk.Label ();
			this.X_label.Name = "X_label";
			this.X_label.LabelProp = global::Mono.Unix.Catalog.GetString ("X");
			this.X_eventBox.Add (this.X_label);
			this.hbox3.Add (this.X_eventBox);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.X_eventBox]));
			w2.Position = 0;
			w2.Expand = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.spinbutton2 = new global::Gtk.SpinButton (-10000D, 10000D, 1D);
			this.spinbutton2.CanFocus = true;
			this.spinbutton2.Name = "spinbutton2";
			this.spinbutton2.Adjustment.PageIncrement = 10D;
			this.spinbutton2.ClimbRate = 0.01D;
			this.spinbutton2.Numeric = true;
			this.hbox3.Add (this.spinbutton2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.spinbutton2]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.Y_eventBox = new global::Gtk.EventBox ();
			this.Y_eventBox.WidthRequest = 32;
			this.Y_eventBox.Name = "Y_eventBox";
			// Container child Y_eventBox.Gtk.Container+ContainerChild
			this.Y_label = new global::Gtk.Label ();
			this.Y_label.Name = "Y_label";
			this.Y_label.LabelProp = global::Mono.Unix.Catalog.GetString ("Y");
			this.Y_eventBox.Add (this.Y_label);
			this.hbox3.Add (this.Y_eventBox);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.Y_eventBox]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.spinbutton4 = new global::Gtk.SpinButton (-10000D, 10000D, 1D);
			this.spinbutton4.CanFocus = true;
			this.spinbutton4.Name = "spinbutton4";
			this.spinbutton4.Adjustment.PageIncrement = 10D;
			this.spinbutton4.ClimbRate = 1D;
			this.spinbutton4.Numeric = true;
			this.hbox3.Add (this.spinbutton4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.spinbutton4]));
			w6.PackType = ((global::Gtk.PackType)(1));
			w6.Position = 3;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.Z_eventBox = new global::Gtk.EventBox ();
			this.Z_eventBox.WidthRequest = 32;
			this.Z_eventBox.Name = "Z_eventBox";
			// Container child Z_eventBox.Gtk.Container+ContainerChild
			this.Z_label = new global::Gtk.Label ();
			this.Z_label.Name = "Z_label";
			this.Z_label.LabelProp = global::Mono.Unix.Catalog.GetString ("Z");
			this.Z_eventBox.Add (this.Z_label);
			this.hbox3.Add (this.Z_eventBox);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.Z_eventBox]));
			w8.PackType = ((global::Gtk.PackType)(1));
			w8.Position = 4;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.spinbutton3 = new global::Gtk.SpinButton (-10000D, 10000D, 1D);
			this.spinbutton3.CanFocus = true;
			this.spinbutton3.Name = "spinbutton3";
			this.spinbutton3.Adjustment.PageIncrement = 10D;
			this.spinbutton3.ClimbRate = 1D;
			this.spinbutton3.Numeric = true;
			this.hbox3.Add (this.spinbutton3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.spinbutton3]));
			w9.PackType = ((global::Gtk.PackType)(1));
			w9.Position = 5;
			w9.Expand = false;
			w9.Fill = false;
			this.Add (this.hbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
