// This file has been generated by the tools/generate_headers.py script

#ifndef __MHE_EVENTS__
#define __MHE_EVENTS__

#include "events/delegate_event_listener.hpp"
#include "events/device.hpp"
#include "events/event.hpp"
#include "events/events_provider.hpp"
#include "events/event_listener.hpp"
#include "events/event_manager.hpp"
#include "events/event_system.hpp"
#include "events/event_type.hpp"
#include "events/keyboard_device.hpp"
#include "events/keyboard_device_impl.hpp"
#include "events/keyboard_event.hpp"
#include "events/mouse_device.hpp"
#include "events/mouse_device_impl.hpp"
#include "events/mouse_event.hpp"
#include "events/system_device.hpp"
#include "events/system_device_impl.hpp"
#include "events/system_event.hpp"

#endif // __MHE_EVENTS__