// This file has been generated by the tools/generate_headers.py script

#ifndef __MHE_SCENE__
#define __MHE_SCENE__

#include "scene/scene.hpp"
#include "scene/camera.hpp"
#include "scene/node.hpp"

#endif // __MHE_SCENE__