// This file has been generated by the tools/generate_headers.py script

#ifndef __MHE_CORE__
#define __MHE_CORE__

#include "core/memory.hpp"
#include "core/noncopyable.hpp"
#include "core/singleton.hpp"
#include "core/types.hpp"
#include "core/compiler.hpp"
#include "core/assert.hpp"
#include "core/config.hpp"
#include "core/array.hpp"
#include "core/fixed_size_vector.hpp"
#include "core/types_cast.hpp"
#include "core/delegate.hpp"

#endif // __MHE_CORE__