// This file has been generated by the tools/generate_headers.py script

#ifndef __MHE_MATH__
#define __MHE_MATH__

#include "math/math_utils.hpp"
#include "math/matrix.hpp"
#include "math/matrix3x3.hpp"
#include "math/quat.hpp"
#include "math/rect.hpp"
#include "math/vector2.hpp"
#include "math/vector3.hpp"
#include "math/vector4.hpp"

#endif // __MHE_MATH__