// This file has been generated by the tools/generate_headers.py script

#ifndef __MHE_CORE__
#define __MHE_CORE__

#include "core/types.hpp"
#include "core/dynarray.hpp"
#include "core/array.hpp"
#include "core/memory.hpp"
#include "core/singleton.hpp"
#include "core/pool.hpp"
#include "core/compiler.hpp"
#include "core/factory.hpp"
#include "core/ref_ptr.hpp"
#include "core/string.hpp"
#include "core/hash.hpp"
#include "core/ref_counter.hpp"
#include "core/delegate.hpp"
#include "core/unique_ptr.hpp"
#include "core/types_cast.hpp"
#include "core/config.hpp"
#include "core/noncopyable.hpp"
#include "core/index_manager.hpp"
#include "core/assert.hpp"
#include "core/fixed_size_vector.hpp"

#endif // __MHE_CORE__