// This file has been generated by the tools/generate_headers.py script

#ifndef __MHE_DEBUG__
#define __MHE_DEBUG__

#include "debug/debug_views.hpp"
#include "debug/default_rdbg_setup.hpp"
#include "debug/imgui_helper.hpp"
#include "debug/light_wrapper.hpp"
#include "debug/profiler.hpp"
#include "debug/rdbg.hpp"

#endif // __MHE_DEBUG__