// This file has been generated by the tools/generate_headers.py script

#ifndef __MHE_THREADS__
#define __MHE_THREADS__

#include "threads/thread_impl.hpp"
#include "threads/thread.hpp"

#endif // __MHE_THREADS__