// This file has been generated by the tools/generate_headers.py script

#ifndef __MHE_APP__
#define __MHE_APP__

#include "app/application.hpp"
#include "app/application_asset_path.hpp"
#include "app/application_config.hpp"

#endif // __MHE_APP__