// This file has been generated by the tools/generate_headers.py script

#ifndef __MHE_GAME__
#define __MHE_GAME__

#include "game/base_view_events_handler.hpp"
#include "game/engine.hpp"
#include "game/game_context.hpp"
#include "game/game_scene.hpp"

#include "game/input/fps_camera_controller.hpp"

#endif // __MHE_GAME__