// This file has been generated by the tools/generate_headers.py script

#ifndef __MHE_RENDER__
#define __MHE_RENDER__

#include "render/window_system.hpp"
#include "render/context.hpp"
#include "render/video_driver.hpp"
#include "render/view.hpp"

#endif // __MHE_RENDER__