// This file has been generated by the tools/generate_headers.py script

#ifndef __MHE_RENDER__
#define __MHE_RENDER__

#include "render/context.hpp"
#include "render/definitions.hpp"
#include "render/gbuffer_helper.hpp"
#include "render/gbuffer_material_system.hpp"
#include "render/image.hpp"
#include "render/instances.hpp"
#include "render/layouts.hpp"
#include "render/light.hpp"
#include "render/material.hpp"
#include "render/material_system.hpp"
#include "render/mesh.hpp"
#include "render/node.hpp"
#include "render/posteffect_material_system.hpp"
#include "render/render_buffer.hpp"
#include "render/render_context.hpp"
#include "render/render_pass.hpp"
#include "render/render_state.hpp"
#include "render/render_target.hpp"
#include "render/shader_program.hpp"
#include "render/skybox_material_system.hpp"
#include "render/texture.hpp"
#include "render/uniforms.hpp"
#include "render/unlit_material_system.hpp"
#include "render/video_driver.hpp"
#include "render/view.hpp"
#include "render/window_system.hpp"

#include "render/utils/simple_meshes.hpp"

#endif // __MHE_RENDER__