//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Gtk;
using mhe;

namespace rdbgc
{
	public class RDBGC
	{
		const string DEFAULT_HOST = "127.0.0.1";
		const int DEFAULT_PORT = 11111;

		static public void Main()
		{
			DataModel dataModel = null;

			Protocol protocol = new Protocol ();
			protocol.Connect(DEFAULT_HOST, DEFAULT_PORT);
			protocol.SendGetAllCommand ((s) =>
				{
					dataModel = new DataModel(s);
				});

			Application.Init ();

			MainWindow main = new MainWindow(dataModel, protocol);
			main.DeleteEvent += OnDelete;
			main.Show();

			Application.Run();
		}

		static public void OnDelete(object o, DeleteEventArgs e)
		{
			Application.Quit();
		}
	}
}

